version: "3"

services: 
  db:
    image: postgres
    container_name: speloarga-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./.db-data:/var/lib/postgresql/data